import type { RaidNeutralBenchmark, RaidOverallTargetProfile } from "./raidTypes";
import {
  TYPE_DPS_INCOMING_CHARGED_DAMAGE_NUMERATOR,
  TYPE_DPS_INCOMING_DAMAGE_NUMERATOR,
  TYPE_DPS_TARGET_DEFENSE,
} from "@pokemongonexus/shared-domain/raid-rules";

export {
  COMFORTABLE_SAFETY_FACTOR,
  DEFAULT_RAID_RELOBBY_SECONDS,
  FRIENDSHIP_DAMAGE_BONUS,
  MEGA_ALLY_DAMAGE_BONUS,
  PARTY_POWER_ACTIVATION_DELAY_SECONDS,
  PARTY_POWER_ACTIVE_CHARGED_MULTIPLIER,
  PARTY_POWER_CHARGED_DAMAGE_BONUS,
  PARTY_POWER_GROUP_SIZE,
  PARTY_POWER_METER_MAX,
  PARTY_POWER_POINTS_PER_MOVE,
  RAID_ATTACKER_TEAM_SIZE,
  RAID_BOSS_ACTION_DELAY_SECONDS,
  RAID_COUNTER_SIMULATION_VARIANT_LIMIT,
  RAID_DODGE_DAMAGE_MULTIPLIER,
  RAID_MONTE_CARLO_MAX_SAMPLES,
  RAID_MONTE_CARLO_MIN_SAMPLES,
  RAID_PARTY_MAX_TRAINERS,
  RAID_PARTY_OPTIMIZER_MAX_BEAM_WIDTH,
  RAID_PARTY_OPTIMIZER_MAX_EVALUATIONS,
  RAID_PARTY_OPTIMIZER_MAX_TEAM_OPTIONS,
  RAID_SAFETY_FACTOR,
  RAID_SIMULATION_ATTACKER_SWAP_SECONDS,
  RAID_SIMULATION_BOSS_ACTION_DELAY_SECONDS,
  RAID_SIMULATION_BOSS_DELAY_OPTIONS_SECONDS,
  RAID_SIMULATION_DODGE_SECONDS,
  RAID_SIMULATION_ENERGY_CAP,
  RAID_SIMULATION_MODEL_VERSION,
  RAID_TIER_PRESETS,
  SHADOW_ATTACKER_DAMAGE_BONUS,
  SHADOW_ATTACKER_DEFENSE_MULTIPLIER,
  SHADOW_BOSS_ENRAGED_ATTACK_MULTIPLIER,
  SHADOW_BOSS_ENRAGED_DEFENSE_MULTIPLIER,
  STAB_DAMAGE_BONUS,
  TYPE_DPS_ER_TDO_EXPONENT,
  TYPE_DPS_INCOMING_CHARGED_DAMAGE_NUMERATOR,
  TYPE_DPS_INCOMING_DAMAGE_NUMERATOR,
  TYPE_DPS_TARGET_DEFENSE,
  WEATHER_DAMAGE_BONUS,
} from "@pokemongonexus/shared-domain/raid-rules";

export const DEFAULT_RAID_NEUTRAL_BENCHMARK: RaidNeutralBenchmark = {
  targetDefense: TYPE_DPS_TARGET_DEFENSE,
  incomingDamageNumerator: TYPE_DPS_INCOMING_DAMAGE_NUMERATOR,
  incomingChargedDamageNumerator: TYPE_DPS_INCOMING_CHARGED_DAMAGE_NUMERATOR,
};
export const RAID_ROUTE_READY_MEASURE = "pokegonexus:raid-route-ready";
export const RAID_COLD_ROUTE_READY_BUDGET_MS = 8000;
export const RAID_WARM_ROUTE_READY_BUDGET_MS = 3000;
export const LEGACY_RAID_TIERS = new Set(["2"]);
export const FALLBACK_OVERALL_TARGET_PROFILES: RaidOverallTargetProfile[] = [
  { types: [], weight: 1 },
];
